export type ModuleLesson = {
  id: string;
  title: string;
  duration: string;
  outcome: string;
};

export type AcademyModule = {
  id: string;
  index: string;
  title: string;
  summary: string;
  signal: string;
  homework: string;
  badge: string;
  lessons: ModuleLesson[];
  quiz: {
    question: string;
    options: string[];
    answer: string;
    explanation: string;
  };
};

export type CadabraPost = {
  id: string;
  author: string;
  rune: string;
  title: string;
  excerpt: string;
  tag: string;
  metrics: string;
  membersOnly?: boolean;
};

export const manifestoLines = [
  'SOVEREIGN REGIME',
  'First 100 Founding Cohort',
  'A capital formation engine disguised as culture.',
  '',
  'Sovereign Regime isn\'t DeFi.',
  'It\'s not RWA either.',
  'It\'s a capital formation engine disguised as culture.',
  '',
  'A NEW MOVEMENT EMERGES',
  'We build the people, and let the people build the business.',
  'Growth is powered exclusively by word-of-mouth and genuine networking.',
  'No hype. No paid ads. No shortcuts.',
  '',
  'We don\'t teach people how to trade crypto.',
  'We teach them how to generate real capital outside the system so they never have to touch what they\'ve already built.',
  'No liquidation. No dependency. No begging for market conditions.',
  'You become the whale before the wealth transfer.',
  '',
  'THE COMPLETE FLOW',
  'Education → Capital → Tokenization → Automation',
  'Not a product list. A complete system.',
  '',
  '1. Learn the edge (Sovereign Regime Academy)',
  '2. Produce fresh capital outside crypto with real discipline',
  '3. Bridge it on-chain through the on-chain Black Card',
  '4. Route it into Sophia Vaults with your mandate',
  '5. The Species (AI agents: Raido, Tide, Circuit, King) compound it 24/7, never sleeping',
  '',
  'Human discipline becomes machine persistence.',
  'Your trading edge becomes autonomous capital generation.',
  '',
  'TWO ASSETS. ONE MISSION.',
  '',
  'Genesis NFT – Sovereign Regime Membership & Lifetime Academy Access',
  '• Lifetime access to the complete Sovereign Regime Academy curriculum (Modules 1-5)',
  '• Sovereign Regime ID card with unique rune + blessing',
  '• Cadabra: the elite, members-only social feed (trading setups, opportunity signals)',
  '• Baseline yield distribution from the entire regime ecosystem',
  '• Recognition as Founding Cohort member (lifetime)',
  '',
  'On-Chain Black Card – Your Tokenized Real-World Assets',
  '• Bring real-world assets on-chain (real estate, portfolios, collectibles, business stakes)',
  '• Earn the on-chain Black Card NFT as proof of ownership and quality',
  '• Deposit Black Cards into Sophia Vaults for yield generation and autonomous compounding',
  '• Scale by acquiring more assets and more Black Cards',
  '• Access secondary credit paths as your vault portfolio grows',
  '',
  'That\'s it. No confusion. No layer-stacking games.',
  'More assets on-chain = more Sophia mandates = more Species agents compounding.',
  '',
  'GENESIS ENROLLMENT – TWO PACKAGES',
  '',
  'The first 100 Genesis NFT members choose their commitment to the Regime:',
  '',
  'GLOBAL LEADER PACKAGE – $497',
  '• Genesis NFT (lifetime membership)',
  '• Leadership status on Sovereign Regime ID card',
  '• Higher baseline yield multiplier across the entire ecosystem (3x founder share)',
  '• Priority access to IRL Sovereign Regime events, private strategy sessions, opportunity calls',
  '• Early access to new asset classes and protocol expansions',
  '• Lifetime recognition as one of the original 100 who architected the movement',
  '• Direct line to protocol community and strategic initiatives',
  '',
  'MEMBER PACKAGE – $247',
  '• Genesis NFT (lifetime membership)',
  '• Full Academy curriculum access (Modules 1-5)',
  '• Sovereign Regime ID card with rune + blessing',
  '• Cadabra social feed access',
  '• Baseline yield distribution from ecosystem',
  '• Founding cohort recognition',
  '',
  'Once the first 100 are claimed, the next wave will have different (and likely higher) entry terms.',
  'This cohort is limited. Intentional. Elite.',
  '',
  'ABRAXAS ACADEMY – THE CURRICULUM',
  '',
  'Module 1 – Market Maker Method + Moving Averages (13/50/200/800 EMA)',
  '  Read liquidity raids. Spot engineered sweeps. Trade the reclaim.',
  '',
  'Module 2 – TDI + 50Bounce Strategy',
  '  Use momentum + reaction zones to generate fresh capital with surgical precision.',
  '',
  'Module 3 – The Black Card & On-Chain Tokenization',
  '  Convert real assets into the on-chain Black Card. Bridge capital on-chain.',
  '',
  'Module 4 – Sophia Vaults & The Species AI Agents',
  '  Write your mandate. Let Raido, Tide, Circuit, and King compound your holdings 24/7.',
  '',
  'Module 5 – Sovereign Finance & Capital Command',
  '  Harden capital. Generate durable yield. Master the SOVEREIGN stakeable stablecoin.',
  '',
  'This is the proven edge. Not theory. Tested. Refined. Battle-hardened.',
  '',
  'ARCHITECTURE – THE REGIME LAYERS',
  '',
  'Layer 1: Academy (Education + Community)',
  '✦ Genesis NFT membership gate',
  '✦ 5-module curriculum (250+ hours of real trading + sovereign finance education)',
  '✦ Progress tracking, homework, quizzes, earned badges',
  '✦ Cadabra: members-only feed for trading signals + opportunity coordination',
  '✦ Weekly opportunity calls + quarterly IRL strategy sessions',
  '',
  'Layer 2: Protocol (Tokenization + Automation)',
  '✦ On-chain Black Card rails for real-world asset tokenization',
  '✦ Sophia Vaults: mandate-driven, agent-executed yield generation',
  '✦ The Species: Raido (trading), Tide (liquidity), Circuit (execution), King (governance)',
  '✦ SOVEREIGN stakeable stablecoin for backend yield and protocol alignment',,
  '',
  'Same language. Same gravity. Same mission.',
  'Capital hardening through education, tokenization, and autonomous compounding.',
  '',
  'COMMUNITY – THE SOVEREIGN REGIME GROWS BY RELATIONSHIP',
  '',
  'Community isn\'t Discord. It\'s coordination at scale.',
  '',
  '✦ Weekly live opportunity calls (trading setup reviews, capital strategy)',
  '✦ Monthly private strategy sessions (vault mandates, agent orchestration)',
  '✦ Quarterly IRL summit in Miami (strategy, culture, networking with founders)',
  '✦ Cadabra signal feed (real-time trading setups, protocol insights, member wins)',
  '✦ Digital scales globally. IRL relationships convert.',
  '',
  'THIS ONLY SCALES THROUGH WORD OF MOUTH',
  '',
  'No paid ads. No marketing budget. No hype cycles.',
  'The Sovereign Regime grows through authentic relationships and proven results.',
  'Real capital. Real yield. Real humans spreading the word because it works.',
  'Word-of-mouth is exponentially faster than any marketing channel.',
  'It\'s the only way to scale without selling.',
  '',
  'TEAM – THE SOVEREIGNS WHO BUILT THIS',
  '',
  'Founder: Acey (@Ac3yway)',
  '  Architect of the regime. Forged the trading methodology. Imagined the Black Card layer.',
  '  Vision holder. The one who said: We\'re not building another crypto product. We\'re building a regime.',
  '',
  'Co-Founders: Neo & Chris',
  '  Orchestrated the on-chain infrastructure. Capital architecture. Protocol rails.',
  '  Built the rails. Made the vision runnable.',
  '',
  'Global Leaders: Swiss & Nick',
  '  Community orchestrators. Protocol deep-dive experts. Strategy architects.',
  '  Building the network that turns vision into movement.',
  '',
  'The right humans came together.',
  'Now we build far beyond any single event.',
  '',
  'WHY THIS WORKS',
  '',
  'The system doesn\'t rely on crypto to function.',
  'If markets go flat, trading discipline still produces capital.',
  'If markets run, the edge accelerates.',
  'That asymmetry is the regime edge.',
  '',
  'WORD OF MOUTH. REAL RESULTS. REAL CAPITAL.',
  '',
  'Genesis NFT is your ticket to lifetime Academy access and Sovereign Regime membership.',
  'The Black Card is how you scale what you build.',
  'Sophia Vaults + The Species is how you compound while sleeping.',
  'SOVEREIGN rewards founding members who show up, build, and share the mission.',,
  '',
  'SOVEREIGN REGIME IS NOT A PRODUCT',,
  '',
  'It\'s a regime.',
  'Regimes don\'t compete.',
  'Regimes absorb.',
  '',
  'Welcome to the first 100.',
  'Welcome to the Sovereign Regime.',,
  'Welcome to the next degree.',
];

export const academyModules: AcademyModule[] = [
  {
    id: 'market-maker-method',
    index: 'I',
    title: 'Market Maker Method + Moving Averages',
    summary: 'Read liquidity raids, anchor bias with EMAs, then watch the algorithm leave its fingerprints before expansion. The first tactical edge in your sovereign arsenal.',
    signal: 'Trading Foundation Layer 01 — The Edge',
    homework: 'Map one London session sweep: locate the flush, mark the reclaim, and explain why the 13/50 structure kept you patient instead of chasing the candle. Real capital is built on patience, not hype.',
    badge: 'Liquidity Cartographer',
    lessons: [
      { id: 'mmm-1', title: 'The algorithmic engine: how dealers profit from retail', duration: '10 min', outcome: 'Spot engineered sweeps instead of chasing candles. Know the boss\'s patterns.' },
      { id: 'mmm-2', title: 'Building the EMA stack: 13/50/200/800 as anchor and signal', duration: '12 min', outcome: 'Use structure, not emotion, to frame continuation and support/resistance.' },
      { id: 'mmm-3', title: 'Session timing: Asia, London, New York and dealer intent', duration: '09 min', outcome: 'Separate real intention from noise at market opens. Know when dealers show their hand.' },
      { id: 'mmm-4', title: 'Trend confirmation: the truth behind the cross', duration: '08 min', outcome: 'Wait for reversal, not anticipate it. Statistically, 70% of trends reward patience.' },
    ],
    quiz: {
      question: 'What confirms a true post-sweep continuation entry in the Market Maker Method?',
      options: [
        'Any breakout candle above the previous high',
        'The 13EMA crossing the 50EMA with price reclaiming structure above it',
        'Volume surge above average on any candle',
      ],
      answer: 'The 13EMA crossing the 50EMA with price reclaiming structure above it',
      explanation: 'The cross is trend confirmation itself — no candle close required. Then you wait for the reclaim to prove the sweep was institutional accumulation, not a trap. This is how we separate signal from noise.',
    },
  },
  {
    id: 'tdi-50bounce',
    index: 'II',
    title: 'TDI + 50Bounce Strategy',
    summary: 'Use TDI momentum and the 50-bounce reaction zone to time entries where retail hesitates and regime capital accumulates. Generate fresh capital to bridge on-chain.',
    signal: 'Trading Foundation Layer 02 — The Execution',
    homework: 'Build a journal with three valid 50-bounce setups (with MBLC + MBLB + CTSFA confluence) and one fake-out you skipped with discipline. This journal is your proof of edge.',
    badge: 'Bounce Jurist',
    lessons: [
      { id: 'tdi-1', title: 'TDI pressure and release: reading momentum without false signals', duration: '11 min', outcome: 'Treat TDI as pressure context for timing, not as a magic button.' },
      { id: 'tdi-2', title: 'The continuation equation: SFA + CTSFA + MBLC + MBLB anatomy', duration: '13 min', outcome: 'Know exactly the four-part setup that separates valid continuations from noise.' },
      { id: 'tdi-3', title: 'The 50-bounce reaction zone and invalidation triggers', duration: '09 min', outcome: 'Understand where continuation enters and what kills it (reverse 13/50 cross).' },
      { id: 'tdi-4', title: 'Stacking confluence without overfitting: when to filter, when to trade', duration: '08 min', outcome: 'Fewer, cleaner entries. Higher conviction. Lower drawdown.' },
    ],
    quiz: {
      question: 'Why does the 50-bounce matter inside the full framework versus in isolation?',
      options: [
        'It provides a universal signal in every market condition',
        'It narrows the reaction zone when paired with TDI momentum confirmation and the EMA stack',
        'It removes the need for stops or risk management',
      ],
      answer: 'It narrows the reaction zone when paired with TDI momentum confirmation and the EMA stack',
      explanation: 'The 50-bounce alone is just a level. Add TDI pressure (MBLC), add the continuation Shark Fin (SFA + CTSFA), and suddenly you have a reaction zone where retail often hesitates. Confluence builds conviction. Conviction builds capital.',
    },
  },
  {
    id: 'black-card-tokenization',
    index: 'III',
    title: 'The On-Chain Black Card & Asset Tokenization',
    summary: 'Convert real-world assets into the on-chain Black Card — humanity\'s first institutional-grade tool for tokenizing and scaling real value. No hype. Pure capital structuring.',
    signal: 'Sovereign Path Layer 01 — Bridge to On-Chain',
    homework: 'Draft one real asset thesis (real estate, portfolio, business stake, collectibles) that should become an on-chain Black Card NFT. Define the core metadata that proves its quality and invites secondary capital and yield paths.',
    badge: 'Black Card Architect',
    lessons: [
      { id: 'tok-1', title: 'Why on-chain Black Card tokenization works: the bridge moment from off-chain to on-chain sovereignty', duration: '12 min', outcome: 'Understand how real assets become liquid, scalable, and yield-generating across borders and systems.' },
      { id: 'tok-2', title: 'Black Card metadata: structuring assets that institutions can understand and fund', duration: '11 min', outcome: 'Build asset records with provenance, valuation, and yield potential that open doors and create velocity.' },
      { id: 'tok-3', title: 'Primary to secondary: how narrative and structure become capital velocity', duration: '09 min', outcome: 'Craft tokenization stories that attract capital, community, and autonomous compounding mechanisms.' },
      { id: 'tok-4', title: 'Strategic on-chain deployment of your real assets', duration: '08 min', outcome: 'Move real assets on-chain with clarity and structure. Stay sovereign. Maintain full control.' },
    ],
    quiz: {
      question: 'What transforms an on-chain Black Card NFT from a static record into an active capital generator?',
      options: [
        'Holding it for 90 days',
        'Having structured metadata that proves asset quality and opens access to Sophia Vaults, yield strategies, and secondary credit paths',
        'Promoting it on social media',
      ],
      answer: 'Having structured metadata that proves asset quality and opens access to Sophia Vaults, yield strategies, and secondary credit paths',
      explanation: 'The on-chain Black Card is only as powerful as the data it carries. Strong metadata = trust. Trust = audience. Audience = capital routes, yield vaults, secondary markets, cross-chain liquidity — all emerge from bulletproof asset records.',
    },
  },
  {
    id: 'sophia-species',
    index: 'IV',
    title: 'Sophia Vaults & The Species AI Agents',
    summary: 'Vault mandates meet autonomous agents. Sophia turns static Black Cards into 24/7 compounding systems. The Species (Raido, Tide, Circuit, King) executes while you build.',
    signal: 'Sovereign Path Layer 02 — Autonomous Compounding',
    homework: 'Design one Sophia Vault mandate for a Black Card asset: (1) agent permissions, (2) yield targets, (3) one hard capital protection rule, (4) what triggers manual override. Your mandate is your constitution.',
    badge: 'Sophia Warden',
    lessons: [
      { id: 'soph-1', title: 'Vault logic: mandate design while keeping your capital whole', duration: '14 min', outcome: 'Write vault instructions that tell agents what to do but not how, preserving your sovereignty and capital safety.' },
      { id: 'soph-2', title: 'The Species layer: Raido, Tide, Circuit, King—when each agent executes', duration: '12 min', outcome: 'Know which Species agent fills which role and why orchestration of multiple minds beats monolithic AI.' },
      { id: 'soph-3', title: 'The 50Bounce inside Sophia: how Raido compounds your Black Card 24/7 without sleeping', duration: '10 min', outcome: 'Your trading edge becomes autonomous capital generation. The algorithm works while you scale.' },
      { id: 'soph-4', title: 'Monitoring, trust, and disciplined human override authority', duration: '09 min', outcome: 'The Species exists to serve your will. Stay sovereign. Override early when drift appears.' },
    ],
    quiz: {
      question: 'What is the correct relationship between you, your Sophia mandate, and the Species agents?',
      options: [
        'The agent grows independent and makes strategic decisions without your input',
        'You write a mandate, the Species executes within bounds, you retain full override authority and sovereignty',
        'You avoid manual oversight to preserve the purity of machine learning',
      ],
      answer: 'You write a mandate, the Species executes within bounds, you retain full override authority and sovereignty',
      explanation: 'Species agents are instruments of your will. Your mandate is the constitution. The agent\'s job is flawless execution, not strategy. When the agent drifts from mandate, you override. Full stop. Your capital, your rules.',
    },
  },
  {
    id: 'sovereign-finance',
    index: 'V',
    title: 'Sovereign Finance, Capital Command & Sovereign',
    summary: 'Close the regime: capital hardening, durable yield power, and SOVEREIGN — the stakeable stablecoin that rewards Sovereign Regime founders. Generate revenue, then compound it. Command your wealth across all cycles.',
    signal: 'Sovereign Path Layer 03 — Capital Command & Yield Authority',
    homework: 'Write your sovereign capital constitution: (1) deployment rules for fresh capital, (2) defense/profit-taking rules, (3) what you absolutely refuse to finance, (4) your durable yield draw rate. This is your financial sovereignty document.',
    badge: 'Capital Regent',
    lessons: [
      { id: 'fin-1', title: 'Antifragility and capital hardening: building wealth that survives and scales across all conditions', duration: '12 min', outcome: 'Protect dry powder while compounding. Understand the difference between growth that lasts and fragility that breaks.' },
      { id: 'fin-2', title: 'Durable yield vs. vanity APY: knowing what truly compounds for decades', duration: '10 min', outcome: 'Separate sustainable yield from marketing yield. Know when to harvest, when to wait, when to ride. Revenue first.' },
      { id: 'fin-3', title: 'The sovereign mindset: deploying capital with intent and precision', duration: '09 min', outcome: 'Build positions that survive. No panic. No surprises. Strategic clarity across bull and bear.' },
      { id: 'fin-4', title: 'SOVEREIGN: the stakeable stablecoin and protocol yield layer that rewards founders', duration: '08 min', outcome: 'Understand how SOVEREIGN rewards Regime founders with sustainable, protocol-backed yields. Revenue, not hype.' },
    ],
    quiz: {
      question: 'What is sovereign finance in the Sovereign Regime?',
      options: [
        'Maximizing APY from any source regardless of risk exposure',
        'Converting all capital into volatile assets to capture every market cycle',
        'Using capital to preserve autonomy, optionality, and long-term strategic command across all conditions and cycles',
      ],
      answer: 'Using capital to preserve autonomy, optionality, and long-term strategic command across all conditions and cycles',
      explanation: 'The point of capital is not motion. The point is sovereignty and command. More dry powder. More optionality. More decades to compound. The regime that stays whole and intact wins. That\'s true sovereign finance.',
    },
  },
];

export const cadabraPosts: CadabraPost[] = [
  {
    id: 'post-1',
    author: 'Rune-018',
    rune: 'ᚱ',
    title: 'London sweep into 20/50 reclaim on SOL',
    excerpt: 'Waited for the engineered flush, then scaled in only after the reclaim printed above session low liquidity. Clean 2.7R.',
    tag: 'Trading Setup',
    metrics: '94 echoes · 21 blessings',
  },
  {
    id: 'post-2',
    author: 'House Vanta',
    rune: '☍',
    title: 'Cadabra clip: ranked win with regime comms overlay',
    excerpt: 'Fast edit from tonight’s stack. Gaming clips stay because timing, poise, and systems thinking carry across domains.',
    tag: 'Gaming Clip',
    metrics: '61 echoes · 9 reposts',
  },
  {
    id: 'post-3',
    author: 'Sophia Desk',
    rune: '✦',
    title: 'Vault mandate thread: when to rotate out of passive yield',
    excerpt: 'Premium breakdown of the moment a yield vehicle stops serving sovereignty and starts renting your attention.',
    tag: 'Members Signal',
    metrics: 'Genesis only · 13 sealed replies',
    membersOnly: true,
  },
  {
    id: 'post-4',
    author: 'Rune-227',
    rune: '𓂀',
    title: 'Black Card mint storyboard for a Miami duplex',
    excerpt: 'Shot list, metadata order, and launch sequence for turning a boring asset deck into a compelling tokenization narrative.',
    tag: 'Tokenization',
    metrics: '47 echoes · 5 citations',
  },
];

export const blessings = [
  'Blessed in volatility. Untouched by panic.',
  'Your patience compounds faster than their hype.',
  'Fortune follows those who can hold formation.',
  'Capital obeys the one who can remain cold.',
  'Your rune sees the trap before the crowd names it.',
];

export const runes = ['ᚱ', '☍', '✦', '𓂀', 'ᛟ', '⌘', '♁', '△'];
